name: financeapp
description: A new Flutter project.

 
 
 
 
 
 
 
 
 
 
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  html: ^0.14.0+3
  bloc: ^3.0.0
  line_awesome_icons: ^1.0.4+2
  font_awesome_flutter: ^8.7.0
  flutter_dynamic_icon: ^0.2.0+1
  line_icons: ^0.2.0 
  crypto_font_icons: 0.1.0  
  firebase_database: ^3.1.3
  fl_chart: ^0.8.4
  flutter_money_formatter: ^0.8.3
  flutter_staggered_animations: ^0.1.2
  extended_image: ^0.7.1
  url_launcher: ^5.4.2
  cupertino_icons: ^0.1.2
  link_previewer: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


 
 

 
flutter:

   
   
   
  uses-material-design: true
